CREATE DATABASE IF NOT EXISTS sistema_db;
USE sistema_db;
CREATE TABLE usuarios (
    id CHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    zona_horaria VARCHAR(50) DEFAULT 'America/Argentina/Buenos_Aires',
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE tenants (
    id CHAR(36) PRIMARY KEY,
    usuario_id CHAR(36) NOT NULL,
    db_name VARCHAR(100) NOT NULL UNIQUE,
    estado ENUM('CREADO', 'PROVISIONANDO', 'ERROR') DEFAULT 'CREADO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);